client_id = "d94ff539d1b8d69b2ee909a46347c5b4"
name = "soundplace-vault"
application_url = "https://soundplace-vault-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
"https://soundplace-vault-production.up.railway.app/auth/callback"
]

[app_proxy]
url = "https://soundplace-vault-production.up.railway.app/vault"
subpath = "vault"
prefix = "apps"